In [142]:
import numpy as np

In [143]:
a= [10,11,12,13,14,15]
n_a = np.array(a)

In [144]:
n_a

array([10, 11, 12, 13, 14, 15])

In [145]:
n_a[-2]

14

In [146]:
n_a[0:5:2]

array([10, 12, 14])

In [147]:
n_a[0:3]

array([10, 11, 12])

In [148]:
n_a[3:6]

array([13, 14, 15])

In [149]:
n_a[2:4]

array([12, 13])

In [150]:
n_a[1:-1]

array([11, 12, 13, 14])

In [151]:
n_a[::2]

array([10, 12, 14])

In [152]:
n_a[1::2]

array([11, 13, 15])

In [153]:
n_b = np.array([100,101,102,103,104,105])
n_c = np.concatenate([n_a, n_b])

In [154]:
n_c

array([ 10,  11,  12,  13,  14,  15, 100, 101, 102, 103, 104, 105])

In [155]:
np.sum(n_c)

690

In [156]:
np.max(n_c)

105

In [157]:
np.min(n_c)

10

In [158]:
np.average(n_c)

57.5

In [159]:
n_random = np.random.random(10)
n_random

array([0.34677613, 0.19993063, 0.77554482, 0.69502195, 0.98664565,
       0.5236456 , 0.00275428, 0.70926612, 0.06327061, 0.49947033])

In [160]:
np.max(n_random)

0.986645650737524

In [162]:
np.min(n_random)

0.002754276786458454

In [164]:
np.sort(n_random)

array([0.00275428, 0.06327061, 0.19993063, 0.34677613, 0.49947033,
       0.5236456 , 0.69502195, 0.70926612, 0.77554482, 0.98664565])

In [165]:
np.argsort(n_random)

array([6, 8, 1, 0, 9, 5, 3, 7, 2, 4])

In [166]:
np.sort(n_random)[::-1]

array([0.98664565, 0.77554482, 0.70926612, 0.69502195, 0.5236456 ,
       0.49947033, 0.34677613, 0.19993063, 0.06327061, 0.00275428])